### ISSUE TITLE
Improve parseGoogleSpreadsheetURL

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#311]
A user with a google Spreadsheet URL of the form `https://docs.google.com/spreadsheets/u/0/d/.../pubhtml` ran into the issue logged in #310 

The problem is that our parser is not equipped to permit the `/u/0/` part. I don't know if we can find any explicit documentation about the forms these can take, but we could probably just add a `(.*?)` expression between `spreadsheets` and `/d/` and at least solve this specific problem (as well as problems that may come up if people use Google Apps for Business/GAFEducation

**Comment by ashwu** [comment]
Google changes the URL from `/d/` to `/u/(digit)/d` when pasted from the "Publish to the Web" window on the spreadsheet into the search bar on browser. Maybe unrelated, but interesting.

**Comment by ashwu** [comment]
Fixed; ready to be checked.

**Comment by JoeGermuska** [comment]
@ashwu is this on a branch? When I merge master and use [this `.../u/0/...` url](https://docs.google.com/spreadsheets/u/0/d/1a8jYcSMWGXupicLJhtNAhkQfta8Fc5qKinDIJtroOAI/pubhtml) I still get no preview and no message.

**Comment by JoeGermuska** [comment]
verified. thanks!
